steps:
  - label: ":docker: build docker image"
    command:
      - ".buildkite/steps/build-image.sh"
      - ".buildkite/steps/upload-image.sh"

  - wait

  - label: ":cop::skin-tone-2: deploy check"
    command: ".buildkite/steps/deploy-test.sh"
    timeout: 90

  - wait

  - label: ":floppy_disk: publish image"
    command: ".buildkite/steps/publish-image.sh"
    branches: "master develop ci-* v*.*.*"
